apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres
          env:
          - name: POSTGRES_PASSWORD
            value: "admin"
          ports:
            - name: http
              containerPort: 5432

