apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3lhc2hhcml0aGExMjMuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJ2YW5uZW1yZWRkaS5oQHVmbC5lZHUiLCJwYXNzd29yZCI6IlNhaGl0aGFAMTQzIiwiZW1haWwiOiJ2YW5uZW1yZWRkaS5oQHVmbC5lZHUiLCJhdXRoIjoiZG1GdWJtVnRjbVZrWkdrdWFFQjFabXd1WldSMU9sTmhhR2wwYUdGQU1UUXoifX19
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
