name: Java CI

on: [push]
env:
  namespace: test
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yasharitha123.jfrog.io/docker/restapi:${{ github.sha }}
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: practice 
          cluster-name: PRACTICE
            
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
        
      - name: create namespace  
        run: |
         kubectl create ns ${{env.namespace}}
        
      - name: create secret
        run: |
         kubectl create -f src/secret.yaml -n ${{env.namespace}}
         kubectl create -f src/secretdb.yaml -n ${{env.namespace}}
         kubectl create -f src/configmap.yaml -n ${{env.namespace}}
     
      - name: Helm tool installer
        id: install-helm
        uses: Azure/setup-helm@v3
        
      - name:  create helm chart
        run: |
          helm package src/helm
          helm install helm src/helm -n ${{env.namespace}} --set imagename=yasharitha123.jfrog.io/docker/restapi:${{ github.sha }}
 

     
