name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yasharitha123.jfrog.io/docker/restapi:${{ github.sha }}
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: practice 
          cluster-name: PRACTICE
            
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Create secret in Kubernetes cluster
        uses: azure/k8s-create-secret@v2
        with:
          namespace: 'scratchpay'
          secret-type: 'generic'
          secret-name: azure-storage
          data: eyJhdXRocyI6eyJodHRwczovL3lhc2hhcml0aGExMjMuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJ2YW5uZW1yZWRkaS5oQHVmbC5lZHUiLCJwYXNzd29yZCI6IlNhaGl0aGFAMTQzIiwiZW1haWwiOiJ2YW5uZW1yZWRkaS5oQHVmbC5lZHUiLCJhdXRoIjoiZG1GdWJtVnRjbVZrWkdrdWFFQjFabXd1WldSMU9sTmhhR2wwYUdGQU1UUXoifX19


