name: databasescripts

on: workflow_dispatch

env:
  namespace: test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: practice 
          cluster-name: PRACTICE
            
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3    
      - name: copy sql file to helm chart
        run: |
           kubectl  cp python_database_scripts/userdb.sql  $(kubectl get pods -n ${{env.namespace}} -o=name | grep postgres | sed "s/^.\{4\}//"):/ -n ${{env.namespace}}
           kubectl  exec  -it $(kubectl get pods -n ${{env.namespace}} -o=name | grep postgres | sed "s/^.\{4\}//") bash -n ${{env.namespace}}  -- /bin/bash -c "psql -U postgres --file python_database_scripts/userdb.sql"
         
