# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Install docker
      uses: docker/setup-docker@v1  
    - name: build postgress image
      run: |
         docker pull postgres
         docker container run --name postgresdb -e POSTGRES_PASSWORD=admin -d -p 0.0.0.0:5432:5432 postgres
         docker exec -it postgresdb psql -U postgres -f userdb.sql
    - name: build application image
      run: |
         docker build -t restapi . --platform=linux/arm64
         docker  container run --name restapi  -e SQL_HOST=localhost -e SQL_DB_NAME=userdb -e SQL_USERNAME=postgres -e SQL_PASSWORD=admin -d -p 8080:8080 restapi

