name: Python CD

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: execute py script # run main.py
      run: python testscripts.py
