name: Python CD

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script # run main.py
      run: python testscripts.py
