name: Python CD

on: [workflow_dispatch]
env:
  DATABASE_URL: "http://20.246.157.172:8080/v1/users"
  CSV_URL: "python_database_scripts/data.csv"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r python_database_scripts/requirements.txt

    - name: execute py script # run main.py
      run: DATABASE_URL=${{ DATABASE_URL }} CSV_URL=${{ CSV_URL }} python python_database_scripts/testscripts.py
